/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDialogFlowScopeProvider extends DelegatingScopeProvider {
}
