/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.scoping;

import dk.sdu.mmmi.mdsd.scoping.AbstractDialogFlowScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DialogFlowScopeProvider extends AbstractDialogFlowScopeProvider {
}
