/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.ui;

import dk.sdu.mmmi.mdsd.ui.AbstractDialogFlowUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DialogFlowUiModule extends AbstractDialogFlowUiModule {
  public DialogFlowUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
