/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.validation;

import dk.sdu.mmmi.mdsd.validation.AbstractDialogFlowValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DialogFlowValidator extends AbstractDialogFlowValidator {
}
