/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.DialogFlowRuntimeModule;
import dk.sdu.mmmi.mdsd.DialogFlowStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DialogFlowIdeSetup extends DialogFlowStandaloneSetup {
  @Override
  public Injector createInjector() {
    DialogFlowRuntimeModule _dialogFlowRuntimeModule = new DialogFlowRuntimeModule();
    DialogFlowIdeModule _dialogFlowIdeModule = new DialogFlowIdeModule();
    return Guice.createInjector(Modules2.mixin(_dialogFlowRuntimeModule, _dialogFlowIdeModule));
  }
}
