/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.ide;

import dk.sdu.mmmi.mdsd.ide.AbstractDialogFlowIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DialogFlowIdeModule extends AbstractDialogFlowIdeModule {
}
