/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DialogFlowUiModule extends AbstractDialogFlowUiModule {
}
