/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.dialogFlow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getType <em>Type</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getList <em>List</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getActionValue()
 * @model
 * @generated
 */
public interface ActionValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getActionValue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Entity)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getActionValue_Type()
   * @model
   * @generated
   */
  Entity getType();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Entity value);

  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(String)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getActionValue_List()
   * @model
   * @generated
   */
  String getList();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.ActionValue#getList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #getList()
   * @generated
   */
  void setList(String value);

} // ActionValue
