/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.dialogFlow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getPhrase <em>Phrase</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getResponse <em>Response</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getIntent()
 * @model
 * @generated
 */
public interface Intent extends Declaration
{
  /**
   * Returns the value of the '<em><b>Phrase</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phrase</em>' containment reference.
   * @see #setPhrase(Phrases)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getIntent_Phrase()
   * @model containment="true"
   * @generated
   */
  Phrases getPhrase();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getPhrase <em>Phrase</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phrase</em>' containment reference.
   * @see #getPhrase()
   * @generated
   */
  void setPhrase(Phrases value);

  /**
   * Returns the value of the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' containment reference.
   * @see #setResponse(Responses)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getIntent_Response()
   * @model containment="true"
   * @generated
   */
  Responses getResponse();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getResponse <em>Response</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response</em>' containment reference.
   * @see #getResponse()
   * @generated
   */
  void setResponse(Responses value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Actions)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getIntent_Action()
   * @model containment="true"
   * @generated
   */
  Actions getAction();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.Intent#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Actions value);

} // Intent
