/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.dialogFlow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Responses</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.Responses#getResponses <em>Responses</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getResponses()
 * @model
 * @generated
 */
public interface Responses extends EObject
{
  /**
   * Returns the value of the '<em><b>Responses</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.dialogFlow.ResponseValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Responses</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getResponses_Responses()
   * @model containment="true"
   * @generated
   */
  EList<ResponseValue> getResponses();

} // Responses
