/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.dialogFlow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.dialogFlow.ResponseValue#getResponse <em>Response</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getResponseValue()
 * @model
 * @generated
 */
public interface ResponseValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Response</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' attribute.
   * @see #setResponse(String)
   * @see dk.sdu.mmmi.mdsd.dialogFlow.DialogFlowPackage#getResponseValue_Response()
   * @model
   * @generated
   */
  String getResponse();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.dialogFlow.ResponseValue#getResponse <em>Response</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response</em>' attribute.
   * @see #getResponse()
   * @generated
   */
  void setResponse(String value);

} // ResponseValue
