/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.DialogFlowRuntimeModule;
import dk.sdu.mmmi.mdsd.DialogFlowStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DialogFlowIdeSetup extends DialogFlowStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DialogFlowRuntimeModule(), new DialogFlowIdeModule()));
	}
	
}
