/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.tests;

import dk.sdu.mmmi.mdsd.tests.DialogFlowInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(DialogFlowInjectorProvider.class)
@SuppressWarnings("all")
public class DialogFlowParsingTest {
}
