/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.parser.antlr.internal.InternalDialogFlowParser;
import dk.sdu.mmmi.mdsd.services.DialogFlowGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DialogFlowParser extends AbstractAntlrParser {

	@Inject
	private DialogFlowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDialogFlowParser createParser(XtextTokenStream stream) {
		return new InternalDialogFlowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DialogFlowSystem";
	}

	public DialogFlowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DialogFlowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
