/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd;

import dk.sdu.mmmi.mdsd.AbstractDialogFlowRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DialogFlowRuntimeModule extends AbstractDialogFlowRuntimeModule {
}
