/**
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DialogFlowStandaloneSetup extends DialogFlowStandaloneSetupGenerated {
  public static void doSetup() {
    new DialogFlowStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
