/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.dialogFlow.ui.internal.DialogFlowActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DialogFlowUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DialogFlowActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.DialogFlow");
	}

}
