/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DialogFlowStandaloneSetup extends DialogFlowStandaloneSetupGenerated {

	def static void doSetup() {
		new DialogFlowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
