/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DialogFlowStandaloneSetup extends DialogFlowStandaloneSetupGenerated {

	public static void doSetup() {
		new DialogFlowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
